# Site settings
title: "Junteng Liu"
type: website
description: "Personal homepage of Junteng Liu, first-year PhD candidate at HKUST NLP Group."
url: "https://xugng08.github.io"
baseurl: "/LJT-Homepage"
repository: "xugng08/LJT-Homepage"

# Jekyll build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge
permalink: /posts/:year/:month/:day/:title/
paginate: 5
paginate_path: /page:num/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

include:
  - _pages

# Site author (shown in the sidebar)
author:
  name: "Junteng Liu"
  bio: "First-year PhD candidate at HKUST NLP Group."
  email: "jliugi@connect.ust.hk"
  github: "Vicent0205"
  scholar: "https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate"
  twitter: "junteng88716710"

# Collections
collections:
  publications:
    output: true
    permalink: /publication/:name/

# Defaults
defaults:
  - scope:
      path: "_pages"
    values:
      layout: "single"
      author_profile: true
  - scope:
      path: ""
      type: "publications"
    values:
      layout: "single"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
